name: tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the dunfell branch
  push:
    branches:
      - gatesgarth
  pull_request:
    branches:
      - gatesgarth
jobs:
  build:
    name: meta-rauc-demo Build (qemu)
    runs-on: ubuntu-20.04
    timeout-minutes: 720
    env:
      POKY_BRANCH: gatesgarth
    steps:
      - name: Install required packages
        run: |
          sudo apt-get install diffstat
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: meta-rauc-demo
      - name: Clone poky
        run: git clone -b ${{ env.POKY_BRANCH }} git://git.yoctoproject.org/poky
      - name: Clone meta-openembedded
        run: git clone -b ${{ env.POKY_BRANCH }} https://github.com/openembedded/meta-openembedded.git
      - name: Clone meta-rauc
        run: git clone -b ${{ env.POKY_BRANCH }} https://github.com/rauc/meta-rauc.git
      - name: Initialize build directory
        run: |
          source poky/oe-init-build-env build
          bitbake-layers add-layer ../meta-rauc
          bitbake-layers add-layer ../meta-rauc-demo/meta-rauc-qemux86
          echo 'INHERIT += "rm_work"' >> conf/local.conf
          echo 'DISTRO_FEATURES_remove = "alsa bluetooth usbgadget usbhost wifi nfs zeroconf pci 3g nfc x11 opengl ptest wayland vulkan"' >> conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* http://195.201.147.117/sstate-cache/PATH"' >> conf/local.conf
      - name: Build qemu-demo-bundle
        run: |
          source poky/oe-init-build-env build
          bitbake rauc qemu-demo-bundle
